[package]
name = "dragonbones_macroquad_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
macroquad = "0.4.13"
serde_json = "1.0.137"
zip = "2.2.2"

[dependencies.rusty_dragonbones]
path = "../rusty_dragonbones"
